name: "SHARKEY.TS CI"
on: [push]
env:
  BLAHAJ_API_TOKEN: ${{ secrets.BLAHAJ_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.43.3
      - name: "Run tests."
        run: deno test --allow-env --allow-net
      - name: "Generate documentation."
        run: deno doc --html --name="Sharkey.ts" ./mod.ts
      - name: "Disable Jekyll."
        run: touch .nojekyll && mv .nojekyll ./docs
      - name: "Deploy the documentation."
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
